install: carthage update --platform iOS
language: swift
os: osx
osx_image: xcode9.3
script:
  xcodebuild -scheme SwiftDiscogs -project SwiftDiscogs.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' test
after_success:
  bash <(curl -s https://codecov.io/bash)

