install: carthage update --platform iOS
language: swift
os: osx
osx_image: xcode9.3
script:
  xcodebuild -scheme SwiftDiscogs -project SwiftDiscogs.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' test
after_success:
  bash <(curl -s https://codecov.io/bash)

