install: 
language: swift
os: osx
osx_image: xcode12.2
script:
  xcodebuild -scheme SwiftDiscogs -project SwiftDiscogs.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.2' test
after_success:
  bash <(curl -s https://codecov.io/bash)
